# Generated by Django 5.2.16 on 2026-07-21 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxRuleSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("jurisdiction", models.CharField(default="MX", max_length=50)),
                (
                    "effective_date",
                    models.DateField(help_text="Date this rule set takes effect"),
                ),
                (
                    "published_gazette_ref",
                    models.CharField(
                        blank=True,
                        help_text="Refernce to the Gaceta official / DOF publication",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Darft"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_by",
                    models.CharField(
                        blank=True,
                        help_text="Whi approved this rule set",
                        max_length=255,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["effective_date"],
                "indexes": [
                    models.Index(
                        fields=["jurisdiction", "status", "effective_date"],
                        name="tax_engine__jurisdi_99d453_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("IVA", "IVA / VAT"),
                            ("ISR", "ISR / Income Tax"),
                            ("RETENCION", "Retencion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        blank=True,
                        help_text="Category, income bracket label, or entity type this rule applies to",
                        max_length=100,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "min_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "max_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "fixed_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "formula_expression",
                    models.JSONField(
                        blank=True,
                        help_text="Optional structured expression for non-trivial calculations",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="tax_engine.taxruleset",
                    ),
                ),
            ],
        ),
    ]
