# Generated by Django 5.2.16 on 2026-07-21 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rfc",
                    models.CharField(
                        help_text="Mexican tax ID", max_length=13, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("persona_fisica", "Persona Física"),
                            ("persona_moral", "Persona Moral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("credit", "Credit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="MXN", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="core.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashFlowEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[("inflow", "Inflow"), ("outflow", "Outflow")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "projected",
                    models.BooleanField(
                        default=False, help_text="True if forecasted, False if actual"
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flow_events",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity", "date"], name="core_cashfl_entity__98d4fd_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("qty", models.IntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("turnover_rate", models.FloatField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_snapshots",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity", "sku", "date"],
                        name="core_invent_entity__bc4394_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "source_doc_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reference to source document/invoice",
                        max_length=255,
                    ),
                ),
                ("is_duplicate_flag", models.BooleanField(default=False)),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence in dedup/anomaly flagging",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.category",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account", "date"],
                        name="core_transa_account_b71ea4_idx",
                    )
                ],
            },
        ),
    ]
